### ISSUE TITLE
Moving repo to keras-team

### ISSUE THREAD

**Issue by fchollet** [keras-team/keras-contrib#189]
Please consider moving this repo to the `keras-team` GitHub organization, in order to have all Keras development repos in one place.

@farizrahman4u, you have been invited to be a member of the `keras-team` organization.

Note that as part of such a move, we should start enforcing the same development standards for `keras` and `keras-contrib`, which means:
- 80% + test coverage
- Passing Travis CI build
- enforced PEP8 code style and Keras API conventions & style conventions

Thanks!

**Comment by ahundt** [comment]
I'd imagined a proving ground with a lower barrier to entry where code is hardened over time. Once the quality is high enough and the method is proven across enough applications, I'd expect it to ultimately be deleted from keras-contrib. 

If those are the goals for keras-contrib, a slight tweak to those standards might be sensible.  Could you articulate your thoughts for this? 

One issue is that the keras-contrib tests keep breaking due to keras API changes, Travis CI changes, etc since a chron job is run against keras master. keras-contrib needs to be fixed quite frequently, even when no pull requests are merged. I've just been copying deleted internal keras APIs into keras-contrib to keep it working where I can, unfortunately I don't have enough free cycles to refactor contributions whenever some internal API or another changes. 

Some policies that might help reduce breakage:
1. keras-contrib could only use public keras APIs and copy in anything with a leading underscore to reduce breakage.
2. Perhaps keras should have a `release` branch always set to the latest point release that keras-contrib tracks which would make breakage less common in repositories that track it?
3. It might be nice to make a couple useful internal Keras APIs public, such as `_obtain_input_shape()`, and `_hash_file()`.
