### ISSUE TITLE
densenet memory consumption

### ISSUE THREAD

**Issue by ysyyork** [keras-team/keras-contrib#203]
I try to use densenet to train my model but the memory consumption is too big. I use the same architecture but change densenet to resnet50, tho the total parameter number of resnet50 is much larger than densenet, I keep on getting out of memory error for densenet while resnet50 runs well. 

https://github.com/liuzhuang13/DenseNet/tree/master/models

It seems the implementation affects densenet a lot. Is there a plan to optimize memory usage of the current densenet?

**Comment by ahundt** [comment]
Thanks for the report! We know about the problem but we cannot address this issue due to the outstanding in tensorflow itself https://github.com/tensorflow/tensorflow/issues/12948. Please report that you are able to duplicate the problem at that link so it can be prioritized!

As for the other backends I haven't tried them and thus cannot comment about them. Since we can't do anything about it from here I'm closing this issue. Sorry!

**Comment by ysyyork** [comment]
Thanks. just reported
