### ISSUE TITLE
Will there ever be a release?

### ISSUE THREAD

**Issue by paulhoule** [keras-team/keras-contrib#328]
Some of us write software for a living and we have a "definition of done" which won't be done if we are always running dependencies out of somebody's source code respository.

Will there be releases of keras-contrib?  Or can I just expect that I will always get the same thing when I check out of git because this project is abandoned?

**Comment by gabrieldemarmiesse** [comment]
I'm currently working on making this project come back to life. I am very confident that there will be releases in the future.

**Comment by JohnGiorgi** [comment]
Is there plans to upload `keras-contrib` to PyPI so that it can be installed with `pip install keras-contrib`?

I have uploaded [my own project](https://github.com/BaderLab/saber) to PyPI, but because it depends on `keras-contrib`, trying to install it with `pip install saber` throws the following error:

```
Packages installed from PyPI cannot depend on packages which are not also hosted on PyPI.
saber depends on keras-contrib@ git+https://www.github.com/keras-team/keras-contrib.git
```

**Comment by gabrieldemarmiesse** [comment]
We'll upload to pypi and have a online documentation when we release the v1.0. You can track the progression with the milestone 1.0. I'll be closing this issue in the favor of the milestone. https://github.com/keras-team/keras-contrib/milestone/1

btw, help is welcome :)
