### ISSUE TITLE
Error in BatchRenormalization

### ISSUE THREAD

**Issue by DaniyarM** [keras-team/keras-contrib#374]
Get "TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed. Use `if t is not None:` instead of `if t:` to test if a tensor is defined, and use TensorFlow ops such as tf.cond to execute subgraphs conditioned on the value of a tensor."

In 311 line of /layers/normalization.py: `r = K.stop_gradient(K.clip(r, 1 / self.r_max, self.r_max))`

**Comment by stante** [comment]
The reason for your problem is probably that you are **not** using a Keras version which includes this patch https://github.com/keras-team/keras/commit/0a639230018d0c9e9f12476dc8b1c6e40c2dd0d0, that introduced tensor arguments to the `K.clip()` version in the backend. In keras_contrib a `K.clip()` version was defined which contained that functionality but was removed with https://github.com/keras-team/keras-contrib/commit/b90f2922f05aaaed0f295e8bc68a2fe9cbda80f9#diff-d6bb097e7e1282f9c20bb482c9177a08. 

The patch I mention above is not in Keras 2.2.4, so you have to use the latest version from the git repository via
```
pip install git+https://www.github.com/keras-team/keras.git 
```
@gabrieldemarmiesse I think this issue can be closed because it does not appear if the latest Keras and keras-contrib is used.

**Comment by DaniyarM** [comment]
Thanks for clarifying

**Comment by torinaki** [comment]
@stante I have installed both master versions and seems to get the same error

**Comment by dylan-plummer** [comment]
Hi,

I am still experiencing this issue.  I ran

`pip install git+https://www.github.com/keras-team/keras.git `

to use to latest version but I get the same error:

```
raise TypeError("Using a `tf.Tensor` as a Python `bool` is not allowed. "
TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed. Use `if t is not None:` instead of `if t:` to test if a tensor is defined, and use TensorFlow ops such as tf.cond to execute subgraphs conditioned on the value of a tensor.
```

The lines that causes the error comes from a custom loss function I defined which uses `K.clip()` where `quantile` is a list containing two min and max values between 0 and 1:

```python
min_value = tf.contrib.distributions.percentile(y_true, q=quantile[0] * 100)
max_value = tf.contrib.distributions.percentile(y_true, q=quantile[1] * 100)
y_true = K.clip(y_true, min_value, max_value)
y_pred = K.clip(y_pred, min_value, max_value)
```

**Comment by DaniyarM** [comment]
@dylan-plummer Try `pip install git+https://www.github.com/keras-team/keras.git --upgrade`

**Comment by dylan-plummer** [comment]
@DaniyarM unfortunately that does not fix the issue.  I also tried fully uninstalling Keras and doing a clean install.

**Comment by DaniyarM** [comment]
@dylan-plummer I have no errors after reinstall all from master. Do you use tensorflow backend?

**Comment by dylan-plummer** [comment]
@DaniyarM  Yes I am using tensorflow-gpu 1.10.0

**Comment by DaniyarM** [comment]
@dylan-plummer My version is 1.13.1 Not sure if it can fix your issue but you can try to update it

**Comment by dylan-plummer** [comment]
@DaniyarM Unfortunately that also does not fix the issue.  Interestingly the code works when I only provide a min value to `K.clip()`

The code below works perfectly with no error:

```python
min_value = tf.contrib.distributions.percentile(y_true, q=quantile[0] * 100)
y_true = K.clip(y_true, min_value, None)
y_pred = K.clip(y_pred, min_value, None)
```
